# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19ff66b132ec353ebd59941a7469bd11955998362572411e1a70e5544cd3cfdff1cee1a0472b727adbacf39227fc869951926eeb2e36db9d8da4274bdab540a0

test:
  secret_key_base: e10ec3994ddf294cda88712485d0d64c860809ecc78c5c7927fc4b154dde9b4c75764753aed0740649502f8d549abd42263cf78be28f957a9ca64defbbe3e77d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
